# kitti_confidence.yaml file

siammask_config: "../SiamMask/experiments/siammask_sharp/config_davis.json"
checkpoint: "../SiamMask/experiments/siammask_sharp/SiamMask_DAVIS.pth"
arch: ""
mode: "end_of_track"
dataset: "a2d2"
datapath: "/media/samuki/Elements/"
similarity: "pretrained_autoencoder"
#thresholds: [0.85,0.9,0.95, 0.98]
#thresholds: [0.65,0.7,0.75, 0.8]
autoencoder_classes: 196
#thresholds: [0.95]
seed: 42
random_entries: 5
frames_per_entry: 50