# kitti_confidence.yaml file

siammask_config: "../SiamMask/experiments/siammask_sharp/config_davis.json"
checkpoint: "../SiamMask/experiments/siammask_sharp/SiamMask_DAVIS.pth"
arch: ""
dataset: "a2d2"
datapath: "../a2d2/"
mode: "IoU"
similarity: "confidence_score"
#thresholds: [0.05,0.1,0.15,0.2]
thresholds: [0.9]
autoencoder_classes: 0
seed: 42
random_entries: 5
frames_per_entry: 50 
