# kitti_confidence.yaml file

siammask_config: "../SiamMask/experiments/siammask_sharp/config_davis.json"
checkpoint: "../SiamMask/experiments/siammask_sharp/SiamMask_DAVIS.pth"
arch: ""
dataset: "kitti"
datapath: "../kitti/"
similarity: "pretrained_autoencoder"
thresholds: [0.05,0.1,0.15,0.2]
autoencoder_classes: 196
seed: 42
random_entries: 5
frames_per_entry: 50 
